name: release-guieditor

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }}"
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Copy release
        id: copy_release
        run: |
          mkdir -p RELEASE_ZIP_DIR && cp *.exe RELEASE_ZIP_DIR
          
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: RELEASE_ZIP_DIR/*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
          
